#!/bin/sh
set -eu
cd -- "$(dirname -- "$0")"

if [ ! -d "pack" ]; then
  echo 'Pack does not exist. Run "create" first.'
  exit 1
fi

set +e
gh tailor autoversion --mode new-on-collision --fail pack
res="$?"
set -e

if [ "$res" = 2 ]; then
  echo "Nothing to publish"
  exit 0
elif [ "$res" != 0 ]; then
  echo "Build failed"
  exit 1
fi

gh tailor publish pack
