#!/bin/sh
set -eu
cd -- "$(dirname -- "$0")"

db="integration_test_db"
results="integration_test_results.csv"
rm -rf "$db" "$results"

gh codeql \
  database create \
  --threads 0 \
  -l "{language}" \
  -s integration_test_code \
  -c "./compile" \
  "$db"

gh codeql \
  database analyze \
  --threads 0 \
  --additional-packs pack \
  --format csv \
  --output "$results" \
  "$db" \
  "{outname}"
